SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_TITLE = "Приключения Кролика"
TILE_SCALING = 0.5
PLAYER_MOVEMENT_SPEED = 4
UPDATES_PER_FRAME = 5
GRAVITY = 0.8
PLAYER_JUMP_SPEED = 16


LAYER_NAME_MOVING_PLATFORMS = "Moving Platforms"
LAYER_NAME_PLATFORMS = "Platforms"
LAYER_NAME_WATER = "Water2"


SPRITE_PIXEL_SIZE = 128
GRID_PIXEL_SIZE = SPRITE_PIXEL_SIZE * TILE_SCALING

RIGHT_FACING = 0
LEFT_FACING = 1

